# Uncomment to enable encoder
CONFIG_EC11=y
CONFIG_EC11_TRIGGER_GLOBAL_THREAD=y

# Central (left side) Bluetooth connection settings
# Set max connections to 4 (3 BT profiles + 1 for peripheral connection)
# These settings should ONLY be on the central side
CONFIG_BT_MAX_CONN=4
CONFIG_BT_MAX_PAIRED=4

